#define SPI_HARDWARE_TYPE MD_MAX72XX::FC16_HW
#define SPI_MAX_DEVICES 4
#define SPI_CHIP_SEL_PIN 8

#define SPI_REFRESH_RATE_MILLI 50ul

#define SPI_MOUTH_DEFAULT_BRIGHTNESS 0

#define SPI_MOUTH_HEIGHT 8
#define SPI_MOUTH_WIDTH 32
#define SPI_ZONE_COUNT 1

#define SPI_LED_ON 1
