#define SPI_HARDWARE_TYPE MD_MAX72XX::FC16_HW
#define SPI_MAX_DEVICES 4
#define SPI_CHIP_SEL_PIN 8

#define SPI_DEFAULT_SPRITE_DWELL_TIME 250ul

#define SPI_MOUTH_DEFAULT_BRIGHTNESS 5

#define SPI_MOUTH_HEIGHT 8
#define SPI_MOUTH_WIDTH 32
#define SPI_ZONE_COUNT 1

#define SPI_LED_ON MD_MAX72XX::controlValue_t::ON
#define SPI_LED_OFF MD_MAX72XX::controlValue_t::OFF