#define I2C_ADDRESS_LEFT_NOSE_BOARD 0x70
#define I2C_ADDRESS_LEFT_EYE_BOARD 0x71

#define I2C_ADDRESS_RIGHT_NOSE_BOARD 0x72

#define I2C_EYE_REFRESH_RATE_MILLI 500ul
#define I2C_NOSE_REFRESH_RATE_MILLI 500ul

#define I2C_EYE_DEFAULT_BRIGHTNESS 5
#define I2C_NOSE_DEFAULT_BRIGHTNESS 5

#define I2C_NOSE_WIDTH 8
#define I2C_NOSE_HEIGHT 8

#define I2C_EYE_WIDTH 8
#define I2C_EYE_HEIGHT 16
